### ISSUE TITLE
write out the questions into code

### ISSUE THREAD

**Issue by 68BooGriffith97** [christian5268/SummerExam-MemeReview#7]

**Comment by christian5268** [comment]
Do you believe in god?

**Comment by AdamIreland** [comment]
How do you think these Gospels made a difference to the lives of the people for whom they were written.

**Comment by christian5268** [comment]
Which gospel writer wrote the first gospel Matthew mark, luke or john?

**Comment by christian5268** [comment]
Name one miracle jesus had performed?
